version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_dc
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snlan
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dc
    environment:
      PGADMIN_DEFAULT_EMAIL: youremail@yourdomain
      PGADMIN_DEFAULT_PASSWORD: yourpasswd
    ports:
      - "80:80"
volumes:
  pgdata:
